# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-04 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='type',
            field=models.IntegerField(choices=[(1, b'Resident'), (2, b'Gatekeeper')], default=1),
        ),
    ]
