# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-04 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profile_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='job_title',
        ),
        migrations.AddField(
            model_name='profile',
            name='job_type',
            field=models.IntegerField(choices=[(0, b'Student'), (1, b'Business'), (2, b'Housewife'), (3, b'Self Employed'), (4, b'Private Job'), (5, b'Government Job'), (6, b'Other')], default=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.IntegerField(choices=[(0, b'Resident'), (1, b'Gatekeeper')], default=0),
        ),
    ]
