# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-04 21:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20161105_0219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='job_type',
            new_name='job_title',
        ),
    ]
